UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Teletalk|MobiCash'	WHERE provider = 	'bKash | Dutch-Bangla | Teletalk | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'MCash|Teletalk'	WHERE provider = 	'MCash | Teletalk'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Airtel|Tangaza'	WHERE provider = 	'Safaricom|Airtel|Tangaza'	;
UPDATE cicos_2013 SET provider = 	'Money Gram|Other Service Provider'	WHERE provider = 	'Money Gram|Other Service Provider'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|iPay'	WHERE provider = 	'bKash | Dutch-Bangla | iPay'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Yu Cash|Tangaza'	WHERE provider = 	'Safaricom|Yu Cash|Tangaza'	;
UPDATE cicos_2013 SET provider = 	'bKash|Trust Bank|MobiCash'	WHERE provider = 	'bKash | Trust Bank | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Orange'	WHERE provider = 	'Airtel|Orange'	;
UPDATE cicos_2013 SET provider = 	'Money Gram|Western Union'	WHERE provider = 	'Money Gram|Western Union'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|MCash'	WHERE provider = 	'bKash | Dutch-Bangla | MCash'	;
UPDATE cicos_2013 SET provider = 	'bKash|MCash|MPAY|Prime Cash'	WHERE provider = 	'bKash | MCash | MPAY | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Cooperative Bank|Equity Bank|Family Bank|Diamond Trust Bank'	WHERE provider = 	'Kenya Commercial Bank|Cooperative Bank|Equity Bank|Family Bank|Diamond Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|Mcash|MPAY'	WHERE provider = 	'Dutch-Bangla | Mcash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'PostBank|Cooperative Bank'	WHERE provider = 	'PostBank|Cooperative Bank'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Yu Cash'	WHERE provider = 	'Airtel|Yu Cash'	;
UPDATE cicos_2013 SET provider = 	'PostBank|Family Bank'	WHERE provider = 	'PostBank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|Trust Bank|MPAY'	WHERE provider = 	'Dutch-Bangla | Trust Bank | MPAY'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Easy Cash'	WHERE provider = 	'bKash | Dutch-Bangla | Easy Cash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Mcash|iPay'	WHERE provider = 	'bKash | Dutch-Bangla | Mcash | iPay'	;
UPDATE cicos_2013 SET provider = 	'bKash|Mcash|Ukash|Prime Cash'	WHERE provider = 	'bKash | Mcash | Ukash | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Teletalk'	WHERE provider = 	'bKash | Teletalk'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Cooperative Bank'	WHERE provider = 	'Kenya Commercial Bank|Cooperative Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|MobiCash|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | MobiCash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|MobiCash'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'bKash|MobiCash'	WHERE provider = 	'bKash | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|UKash'	WHERE provider = 	'Dutch-Bangla | UKash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Mcash|Teletalk'	WHERE provider = 	'bKash | Dutch-Bangla | Mcash | Teletalk'	;
UPDATE cicos_2013 SET provider = 	'Cooperative Bank|Equity Bank|Consolidated Bank'	WHERE provider = 	'Cooperative Bank|Equity Bank|Consolidated Bank'	;
UPDATE cicos_2013 SET provider = 	'Money Gram|Western Union|Other Service Provider'	WHERE provider = 	'Money Gram|Western Union|Other Service Provider'	;
UPDATE cicos_2013 SET provider = 	'bKash |Mcash|MPAY'	WHERE provider = 	'bKash |Mcash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Trust bank|MobiCash'	WHERE provider = 	'Trust bank | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|MCash'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | MCash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | MPAY'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Mcash|Prime Cash'	WHERE provider = 	'bKash | Dutch-Bangla | Mcash | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Cooperative Bank|Equity Bank|Chase Bank'	WHERE provider = 	'Kenya Commercial Bank|Cooperative Bank|Equity Bank|Chase Bank'	;
UPDATE cicos_2013 SET provider = 	'PostBank|Cooperative Bank|Equity Bank|Family Bank'	WHERE provider = 	'PostBank|Cooperative Bank|Equity Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'Western Union|Other Service Provider'	WHERE provider = 	'Western Union|Other Service Provider'	;
UPDATE cicos_2013 SET provider = 	'bKash|iPay'	WHERE provider = 	'bKash | iPay'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|Teletalk'	WHERE provider = 	'Dutch-Bangla | Teletalk'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Tangaza'	WHERE provider = 	'Airtel|Tangaza'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|MCash|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | MCash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Orange|Yu Cash'	WHERE provider = 	'Safaricom|Orange|Yu Cash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Diamond Trust Bank'	WHERE provider = 	'Kenya Commercial Bank|Diamond Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|PostBank'	WHERE provider = 	'Kenya Commercial Bank|PostBank'	;
UPDATE cicos_2013 SET provider = 	'Cooperative Bank|Equity Bank|Diamond Trust Bank'	WHERE provider = 	'Cooperative Bank|Equity Bank|Diamond Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|PostBank|Equity Bank|Family Bank'	WHERE provider = 	'Kenya Commercial Bank|PostBank|Equity Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Orange|Yu Cash'	WHERE provider = 	'Airtel|Orange|Yu Cash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Trust Bank|MCash'	WHERE provider = 	'bKash | Trust Bank | MCash'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Yu Cash|Safaricom'	WHERE provider = 	'Airtel|Yu Cash|Safaricom'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Mcash|UKash'	WHERE provider = 	'bKash | Dutch-Bangla | Mcash | UKash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Equity Bank|Family Bank'	WHERE provider = 	'Kenya Commercial Bank|Equity Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'PostBank|Equity Bank|Family Bank'	WHERE provider = 	'PostBank|Equity Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Cooperative Bank|Chase Bank'	WHERE provider = 	'Kenya Commercial Bank|Cooperative Bank|Chase Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|MobiCash|MPAY'	WHERE provider = 	'bKash | MobiCash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Airtel|Yu Cash'	WHERE provider = 	'Safaricom|Airtel|Yu Cash'	;
UPDATE cicos_2013 SET provider = 	'bKash|MPAY|Prime Cash'	WHERE provider = 	'bKash | MPAY | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|Mcash|MobiCash'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | Mcash | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'PostBank|Cooperative Bank|Equity Bank'	WHERE provider = 	'PostBank|Cooperative Bank|Equity Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|MobiCash|Prime Cash'	WHERE provider = 	'bKash | Dutch-Bangla | MobiCash | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'Cooperative Bank|Consolidated Bank'	WHERE provider = 	'Cooperative Bank|Consolidated Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|UKash'	WHERE provider = 	'bKash | UKash'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Airtel|Orange|Yu Cash'	WHERE provider = 	'Safaricom|Airtel|Orange|Yu Cash'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Airtel|Orange'	WHERE provider = 	'Safaricom|Airtel|Orange'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|PostBank|Equity Bank'	WHERE provider = 	'Kenya Commercial Bank|PostBank|Equity Bank'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Orange'	WHERE provider = 	'Safaricom|Orange'	;
UPDATE cicos_2013 SET provider = 	'bKash|MPAY'	WHERE provider = 	'bKash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Equity Bank|Diamond Trust Bank'	WHERE provider = 	'Equity Bank|Diamond Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'Yu Cash|Safaricom'	WHERE provider = 	'Yu Cash|Safaricom'	;
UPDATE cicos_2013 SET provider = 	'Western Union|Express Money'	WHERE provider = 	'Western Union|Express Money'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|Prime Cash'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|Trust bank'	WHERE provider = 	'Dutch-Bangla | Trust bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Mcash|Teletalk|UKash'	WHERE provider = 	'bKash | Dutch-Bangla | Mcash | Teletalk | UKash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Equity Bank|Diamond Trust Bank'	WHERE provider = 	'Kenya Commercial Bank|Equity Bank|Diamond Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Trust bank'	WHERE provider = 	'bKash | Trust bank'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank|Equity Bank|Diamond Trust Bank'	WHERE provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank|Equity Bank|Diamond Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|MCash'	WHERE provider = 	'bKash | MCash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|Mcash|Ukash|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | Mcash | Ukash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Yu Cash|Tangaza'	WHERE provider = 	'Yu Cash|Tangaza'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Mcash|MobiCash|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | Mcash | MobiCash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Orange|Yu Cash|Safaricom'	WHERE provider = 	'Airtel|Orange|Yu Cash|Safaricom'	;
UPDATE cicos_2013 SET provider = 	'MPay|Prime Cash'	WHERE provider = 	'MPay | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'Equity Bank|Family Bank'	WHERE provider = 	'Equity Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash |Mcash|UKash'	WHERE provider = 	'bKash |Mcash | UKash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|Teletalk|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | Teletalk | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Safaricom'	WHERE provider = 	'Airtel|Safaricom'	;
UPDATE cicos_2013 SET provider = 	'Money Gram|Western Union|Express Money'	WHERE provider = 	'Money Gram|Western Union|Express Money'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Prime Cash'	WHERE provider = 	'bKash | Dutch-Bangla | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Family Bank'	WHERE provider = 	'Kenya Commercial Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash |Mcash|Prime Cash'	WHERE provider = 	'bKash |Mcash | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Easy Cash'	WHERE provider = 	'bKash | Easy Cash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank|Family Bank'	WHERE provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|Easy Cash'	WHERE provider = 	'Dutch-Bangla | Easy Cash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Trust Bank|MPAY'	WHERE provider = 	'bKash | Trust Bank | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Cooperative Bank|Family Bank'	WHERE provider = 	'Cooperative Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|MobiCash'	WHERE provider = 	'bKash | Dutch-Bangla | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'Express Money|Other Service Provider'	WHERE provider = 	'Express Money|Other Service Provider'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|MobiCash|UKash'	WHERE provider = 	'bKash | Dutch-Bangla | MobiCash | UKash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Equity Bank'	WHERE provider = 	'Kenya Commercial Bank|Equity Bank'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Tangaza'	WHERE provider = 	'Safaricom|Tangaza'	;
UPDATE cicos_2013 SET provider = 	'bKash|Trust Bank|iPay'	WHERE provider = 	'bKash | Trust Bank | iPay'	;
UPDATE cicos_2013 SET provider = 	'Cooperative Bank|Chase Bank'	WHERE provider = 	'Cooperative Bank|Chase Bank'	;
UPDATE cicos_2013 SET provider = 	'Tangaza|Safaricom'	WHERE provider = 	'Tangaza|Safaricom'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|Mcash|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | Mcash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Cooperative Bank|Equity Bank|Family Bank'	WHERE provider = 	'Kenya Commercial Bank|Cooperative Bank|Equity Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank|Equity Bank|Family Bank'	WHERE provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank|Equity Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'Trust bank|MCash'	WHERE provider = 	'Trust bank | MCash'	;
UPDATE cicos_2013 SET provider = 	'Western Union|Express Money|Other Service Provider'	WHERE provider = 	'Western Union|Express Money|Other Service Provider'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | MPAY'	;
UPDATE cicos_2013 SET provider = 	'Cooperative Bank|Equity Bank'	WHERE provider = 	'Cooperative Bank|Equity Bank'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Orange|Safaricom'	WHERE provider = 	'Airtel|Orange|Safaricom'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|Mcash|Prime Cash'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | Mcash | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|Mcash|Teletalk|UKash'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | Mcash | Teletalk | UKash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Cooperative Bank|Family Bank'	WHERE provider = 	'Kenya Commercial Bank|Cooperative Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|MobiCash'	WHERE provider = 	'Dutch-Bangla | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Yu Cash'	WHERE provider = 	'Safaricom|Yu Cash'	;
UPDATE cicos_2013 SET provider = 	'Money Gram|Express Money'	WHERE provider = 	'Money Gram|Express Money'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Chase Bank'	WHERE provider = 	'Kenya Commercial Bank|Chase Bank'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank'	WHERE provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank'	;
UPDATE cicos_2013 SET provider = 	'Cooperative Bank|Equity Bank|Family Bank'	WHERE provider = 	'Cooperative Bank|Equity Bank|Family Bank'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Cooperative Bank|Equity Bank'	WHERE provider = 	'Kenya Commercial Bank|Cooperative Bank|Equity Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Mcash|MobiCash'	WHERE provider = 	'bKash | Dutch-Bangla | Mcash | MobiCash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Equity Bank|Family Bank|Diamond Trust Bank'	WHERE provider = 	'Kenya Commercial Bank|Equity Bank|Family Bank|Diamond Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|MPAY'	WHERE provider = 	'Dutch-Bangla | MPAY'	;
UPDATE cicos_2013 SET provider = 	'bKash|Prime Cash'	WHERE provider = 	'bKash | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'Orange|Safaricom'	WHERE provider = 	'Orange|Safaricom'	;
UPDATE cicos_2013 SET provider = 	'Dutch-Bangla|MCash'	WHERE provider = 	'Dutch-Bangla | MCash'	;
UPDATE cicos_2013 SET provider = 	'Equity Bank|Chase Bank'	WHERE provider = 	'Equity Bank|Chase Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Trust Bank|Mcash|Teletalk'	WHERE provider = 	'bKash | Dutch-Bangla | Trust Bank | Mcash | Teletalk'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank|Equity Bank'	WHERE provider = 	'Kenya Commercial Bank|PostBank|Cooperative Bank|Equity Bank'	;
UPDATE cicos_2013 SET provider = 	'PostBank|Equity Bank'	WHERE provider = 	'PostBank|Equity Bank'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla'	WHERE provider = 	'bKash | Dutch-Bangla'	;
UPDATE cicos_2013 SET provider = 	'PostBank|Consolidated Bank'	WHERE provider = 	'PostBank|Consolidated Bank'	;
UPDATE cicos_2013 SET provider = 	'Money Gram|Western Union|Express Money|Other Service Provider'	WHERE provider = 	'Money Gram|Western Union|Express Money|Other Service Provider'	;
UPDATE cicos_2013 SET provider = 	'Airtel|Yu Cash|Tangaza'	WHERE provider = 	'Airtel|Yu Cash|Tangaza'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|MPAY|Prime Cash'	WHERE provider = 	'bKash | Dutch-Bangla | MPAY | Prime Cash'	;
UPDATE cicos_2013 SET provider = 	'Kenya Commercial Bank|Cooperative Bank|Family Bank|Diamond Trust Bank'	WHERE provider = 	'Kenya Commercial Bank|Cooperative Bank|Family Bank|Diamond Trust Bank'	;
UPDATE cicos_2013 SET provider = 	'Safaricom|Airtel'	WHERE provider = 	'Safaricom|Airtel'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Easy Cash|MPAY'	WHERE provider = 	'bKash | Dutch-Bangla | Easy Cash | MPAY'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|UKash'	WHERE provider = 	'bKash | Dutch-Bangla | UKash'	;
UPDATE cicos_2013 SET provider = 	'bKash|Dutch-Bangla|Teletalk'	WHERE provider = 	'bKash | Dutch-Bangla | Teletalk'	;

UPDATE cicos_2013 SET provider =	'PrimeTime Mcsl'	WHERE provider = 	'PrimeTime Mcsl,'	;
UPDATE cicos_2013 SET provider =	'Okopedi-Itu Multi-Purpose Co-operative Society Limited'	WHERE provider = 	'Okopedi-Itu Multi-Purpose Co-operative Society Limited,'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|EzyPesa'	WHERE provider = 	'TigoPesa,EzyPesa,'	;
UPDATE cicos_2013 SET provider =	'MTN|Airtel|Warid'	WHERE provider = 	'MTN,Airtel,Warid'	;
UPDATE cicos_2013 SET provider =	'MTN|Airtel|MSente'	WHERE provider = 	'MTN,Airtel,MSente'	;
UPDATE cicos_2013 SET provider =	'MTN|Warid|MSente'	WHERE provider = 	'MTN,Warid,MSente'	;
UPDATE cicos_2013 SET provider =	'NURTW|zonal Office'	WHERE provider = 	'NURTW, zonal Office'	;
UPDATE cicos_2013 SET provider =	'TigoPesa'	WHERE provider = 	'TigoPesa,'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|AirtelCash|EzyPesa|MPesa'	WHERE provider = 	'TigoPesa,AirtelCash,EzyPesa,MPesa'	;
UPDATE cicos_2013 SET provider =	'Omedo Youth|Co-Operative & Daily Contribution Center'	WHERE provider = 	'Omedo Youth, Co-Operative & Daily Contribution Center'	;
UPDATE cicos_2013 SET provider =	'Mutual Benefit Assurance|Microfinance Bank'	WHERE provider = 	'Mutual Benefit Assurance, Microfinance Bank'	;
UPDATE cicos_2013 SET provider =	'Unipon Homes|Savings and Loans Ltd'	WHERE provider = 	'Unipon Homes, Savings and Loans Ltd'	;
UPDATE cicos_2013 SET provider =	'Leverage Homes|Savoings and Loans Ltd'	WHERE provider = 	'Leverage Homes, Savoings and Loans Ltd'	;
UPDATE cicos_2013 SET provider =	'Nigerian Agricultural|Co-operative And Rural Development Bank ltd'	WHERE provider = 	'Nigerian Agricultural,Co-operative  And Rural Development Bank ltd'	;
UPDATE cicos_2013 SET provider =	'Star Microfinance Bank|Ijebu Igbo Customers Meeting Point.'	WHERE provider = 	'Star Microfinance Bank,Ijebu Igbo Customers Meeting Point.'	;
UPDATE cicos_2013 SET provider =	'Bunza motor park|Kebbi State'	WHERE provider = 	'Bunza motor park,Kebbi State'	;
UPDATE cicos_2013 SET provider =	'Technican Association|Tangaza'	WHERE provider = 	'Technican Association, Tangaza'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|MPesa'	WHERE provider = 	'TigoPesa,MPesa'	;
UPDATE cicos_2013 SET provider =	'AirtelCash|EzyPesa'	WHERE provider = 	'AirtelCash,EzyPesa,'	;
UPDATE cicos_2013 SET provider =	'MTN|Airtel|Warid|MCash'	WHERE provider = 	'MTN,Airtel,Warid,MCash'	;
UPDATE cicos_2013 SET provider =	'AirtelCash|MPesa'	WHERE provider = 	'AirtelCash,MPesa'	;
UPDATE cicos_2013 SET provider =	'Airtel|MSente'	WHERE provider = 	'Airtel,MSente'	;
UPDATE cicos_2013 SET provider =	'EzyPesa'	WHERE provider = 	'EzyPesa,'	;
UPDATE cicos_2013 SET provider =	'MTN|MSente'	WHERE provider = 	'MTN,MSente'	;
UPDATE cicos_2013 SET provider =	'NURTW|Maraba Akunza Branch'	WHERE provider = 	'NURTW,Maraba Akunza Branch'	;
UPDATE cicos_2013 SET provider =	'FHA Homes|Savings and Loans Ltd'	WHERE provider = 	'FHA Homes,Savings and Loans Ltd'	;
UPDATE cicos_2013 SET provider =	'NURTW|Bauchi Unit'	WHERE provider = 	'NURTW, Bauchi Unit'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|AirtelCash'	WHERE provider = 	'TigoPesa,AirtelCash,'	;
UPDATE cicos_2013 SET provider =	'AirtelCash'	WHERE provider = 	'AirtelCash,'	;
UPDATE cicos_2013 SET provider =	'Warid|MSente'	WHERE provider = 	'Warid,MSente'	;
UPDATE cicos_2013 SET provider =	'Other|MPesa'	WHERE provider = 	'Other,MPesa'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|AirtelCash|Other|MPesa'	WHERE provider = 	'TigoPesa,AirtelCash,Other,MPesa'	;
UPDATE cicos_2013 SET provider =	'MSente|Other'	WHERE provider = 	'MSente,Other'	;
UPDATE cicos_2013 SET provider =	'AirtelCash|Other|MPesa'	WHERE provider = 	'AirtelCash,Other,MPesa'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|AirtelCash|MPesa'	WHERE provider = 	'TigoPesa,AirtelCash,MPesa'	;
UPDATE cicos_2013 SET provider =	'Oji Central Park'	WHERE provider = 	'Oji Central Park,'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|Other|MPesa'	WHERE provider = 	'TigoPesa,Other,MPesa'	;
UPDATE cicos_2013 SET provider =	'AirtelCash|EzyPesa|MPesa'	WHERE provider = 	'AirtelCash,EzyPesa,MPesa'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|Other'	WHERE provider = 	'TigoPesa,Other,'	;
UPDATE cicos_2013 SET provider =	'Airtel|Warid'	WHERE provider = 	'Airtel,Warid'	;
UPDATE cicos_2013 SET provider =	'MTN|Airtel|Warid|MSente'	WHERE provider = 	'MTN,Airtel,Warid,MSente'	;
UPDATE cicos_2013 SET provider =	'Airtel|MCash'	WHERE provider = 	'Airtel,MCash'	;
UPDATE cicos_2013 SET provider =	'EzyPesa|MPesa'	WHERE provider = 	'EzyPesa,MPesa'	;
UPDATE cicos_2013 SET provider =	'MTN|Airtel|Warid|MSente|Other'	WHERE provider = 	'MTN,Airtel,Warid,MSente,Other'	;
UPDATE cicos_2013 SET provider =	'MTN|Other'	WHERE provider = 	'MTN,Other'	;
UPDATE cicos_2013 SET provider =	'North West Park'	WHERE provider = 	'North West Park,'	;
UPDATE cicos_2013 SET provider =	'Airtel|Warid|MSente'	WHERE provider = 	'Airtel,Warid,MSente'	;
UPDATE cicos_2013 SET provider =	'God''s Favour Park'	WHERE provider = 	'God''s Favour Park,'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|EzyPesa|Other|MPesa'	WHERE provider = 	'TigoPesa,EzyPesa,Other,MPesa'	;
UPDATE cicos_2013 SET provider =	'MTN|Warid'	WHERE provider = 	'MTN,Warid'	;
UPDATE cicos_2013 SET provider =	'MTN|MCash'	WHERE provider = 	'MTN,MCash'	;
UPDATE cicos_2013 SET provider =	'MTN|Airtel'	WHERE provider = 	'MTN,Airtel'	;
UPDATE cicos_2013 SET provider =	'TigoPesa|EzyPesa|MPesa'	WHERE provider = 	'TigoPesa,EzyPesa,MPesa'	;



